name: Build and Deploy shipping microservice to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-java.yaml@main
    with:
      MICROSERVICE: shipping
      IMAGE: shipping
      NAMESPACE: shipping-microservice
      RELEASE: shipping
      WORKING_DIR: ./shipping
      DOCKERFILE_PATH: ./shipping
    secrets: inherit